### ISSUE TITLE
New feature: Daily vaccine injetcions

### ISSUE THREAD

**Issue by JanosAudron** [fabriziomiano/covidashit#26]
Might be helpful to have a daily report about daily vaccine injections, divided by first and second dose.

**Comment by fabriziomiano** [comment]
thanks for opening a request for a new feature, and for the good shout. I might just add two cards (daily first doses, daily second doses) as I did for the pandemic dashboard. By the way, do I personally know you? 😃

**Comment by fabriziomiano** [comment]
The two cards have been added to both the national and regional views. 
I'm closing this request but feel free to open a new one should you have more suggestions.

**Comment by JanosAudron** [comment]
Thank you! Might be interesting to also have a chart showing the trend, like "Percentage of people vaccinated"

**Comment by JanosAudron** [comment]
There is a mistake: if today vaccines are more than yesterday ones, percetage reports "flat trend" instead increasing one
![image](https://user-images.githubusercontent.com/1606318/113258886-c91c7080-92cc-11eb-8b20-8bcb0ccdb640.png)

**Comment by JanosAudron** [comment]
In the national trend, second injections trend report e nevative trend even if counter is increased since yesterday
![image](https://user-images.githubusercontent.com/1606318/113263305-e1db5500-92d1-11eb-9b1f-bc0d6671f432.png)

**Comment by fabriziomiano** [comment]
Thanks for pointing these out!
I'll fix them soon
