### ISSUE TITLE
Errore Pie chart "Somministrazioni per fornitore"

### ISSUE THREAD

**Issue by gaetanosettembre** [fabriziomiano/covidashit#28]
Vorrei evidenziare un problema che si è verificato sicuramente da quanto il vaccino Astrazeneca ha cambiato nome, in particolare nei pie chart relativi alle somministrazioni per fornitore. 
Il numero di dosi somministrate di Vaxzevria (AstraZeneca) comprende già il numero di dosi somministrate in precedenza con AstraZeneca, infatti se si fa la somma di dosi somministrate con Pfizer/BioNTech, Moderna e Vaxzevria (AstraZeneca) si ottiene il numero totale delle somministrazioni. Se aggiungessimo anche quelle dello spicchio identificate solamente con AstraZeneca, si supererebbe il totale.

Sperando di averLe fatto cosa gradita,
un cordiale saluto

**Comment by fabriziomiano** [comment]
Grazie mille della segnalazione. Molto apprezzata. Dovrebbe essere fixata col prossimo update dei dati
