### ISSUE TITLE
People resurrected

### ISSUE THREAD

**Issue by JanosAudron** [fabriziomiano/covidashit#8]
Yesterday have been a very good day, ad 571 people resurrected... :-D
Today a little worse...

![image](https://user-images.githubusercontent.com/1606318/106017877-41926580-60c1-11eb-999f-a14a0dfebb13.png)

**Comment by fabriziomiano** [comment]
I'm not sure I got what you meant..
That card indicates the daily deaths count (today - yesterday) as obtained from the cumulative distribution.
Also, I can't work out where that '-571' you mentioned comes from.

I wouldn't mind if you could extend your thoughts.

In the meanwhile I hope this helps 
![italy](https://user-images.githubusercontent.com/29355604/106307182-51e04700-625f-11eb-81cc-acf170ff5fff.png)

**Comment by JanosAudron** [comment]
I mean, if yesterday there had been minus 541 dead, means that 541 people resurrected 😄
Sorry, I wrote 571 but I meant 541.

**Comment by fabriziomiano** [comment]
I'm not sure what you're trying to do here, but if you're trying to take the piss, I have bad news.

I'll explain myself for other potential readers. 
**The daily deaths count can never be negative, as it's worked out from the total cumulative deaths count.** 
Most importantly, that number -541 is completely made up, as if you perhaps touched the HTML code? How sad would that be?
I'm sorry but I don't have that number anywhere in the DB! 
Chill out man. There were no resurrections :rofl: 

Additionally, to further corroborate the message I'm trying to get across, as the plot attached in my previous comment shows, the daily deaths count has never been negative, and it contains the same data that is shown in the card!

According to what github says, you opened this (fake) issue 3 days ago (Jan the 27th).
On that day, sadly enough, 467 people died as you can check yourself in the attached screenshot. 

![Screenshot from 2021-01-30 11-16-21](https://user-images.githubusercontent.com/29355604/106353698-b990a380-62ec-11eb-826f-21a63d3b8b78.png)

I'm closing the issue, as it isn't one.

**Comment by JanosAudron** [comment]
I'm sorry, I can assure you I didn't modify anything. I tried to joke on a bug, or about what I thought it was, but obviously I failed... 😏

**Comment by fabriziomiano** [comment]
Fair enough. I want to believe you.
The problem still holds though: I cannot replicate what you saw. 
By going back one more day (Jan the 26th) the daily deaths count was 541, and the day before (Jan the 25th) it was 420, so there's no way for me to check where that "-541" you have in your screenshot came from. 

Ultimately, as I still find it useful when people constructively open issues, the next time you might find something that doesn't look right, please provide me with the "latest update" you can find at the top-right corner of the pandemic dashboard, and a screenshot of the whole pandemic dashboard. 

Thanks
Have a lovely weekend.

**Comment by JanosAudron** [comment]
Probably was not your fault. Looking at Protezione Civile repository, day 27th has been only day with 2 commits. Probably they published wrong data. Then, days 28th 29th and 30th have been modified 20h ago.
https://github.com/pcm-dpc/COVID-19/commits/master

**Comment by fabriziomiano** [comment]
It might as well be the case. I manage the mongo collections where the data for the web app live, by updating the old data (in case of corrections) and adding the new data, at every push they send. Then, I guess you might have stumbled upon their error which propagated up to the dashboard.
